/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactType = IDL.Variant({
  'email' : IDL.Null,
  'phone' : IDL.Null,
});
export const Reservation = IDL.Record({
  'id' : IDL.Nat,
  'contact' : IDL.Text,
  'contactType' : ContactType,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'guestName' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'partySize' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createReservation' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        ContactType,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'getReservation' : IDL.Func([IDL.Nat], [IDL.Opt(Reservation)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactType = IDL.Variant({ 'email' : IDL.Null, 'phone' : IDL.Null });
  const Reservation = IDL.Record({
    'id' : IDL.Nat,
    'contact' : IDL.Text,
    'contactType' : ContactType,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'guestName' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'partySize' : IDL.Nat,
  });
  
  return IDL.Service({
    'createReservation' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ContactType,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'getReservation' : IDL.Func([IDL.Nat], [IDL.Opt(Reservation)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };